# Generated by Django 2.2.4 on 2019-12-06 19:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gcmv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bore_id', models.CharField(max_length=20)),
                ('job_id', models.CharField(max_length=20)),
                ('instrument', models.CharField(max_length=20)),
                ('chemical_id', models.CharField(max_length=20)),
                ('measurement_value', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='mscnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bore_id', models.CharField(max_length=20)),
                ('job_id', models.CharField(max_length=20)),
                ('instrument', models.CharField(max_length=20)),
                ('chemical_id', models.CharField(max_length=20)),
                ('measurement_value', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
