# Generated by Django 2.1.5 on 2019-01-07 15:56

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=200)),
                ('deviceId', models.CharField(max_length=200)),
                ('chemicalId', models.CharField(max_length=200)),
                ('concentration', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('position', geoposition.fields.GeopositionField(default='0,0', max_length=42)),
            ],
        ),
    ]
