# Generated by Django 2.2.4 on 2019-11-22 20:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drf_Jobid',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name=10)),
                ('label', models.TextField(verbose_name=10)),
            ],
            options={
                'db_table': 'drf_jobid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_Measurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bore_id', models.CharField(max_length=20)),
                ('job_id', models.CharField(max_length=20)),
                ('device_id', models.CharField(max_length=20)),
                ('chemical_id', models.CharField(max_length=20)),
                ('concentration', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'drf_measurement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_Timestamp',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False)),
                ('label', models.DateTimeField()),
            ],
            options={
                'db_table': 'drf_timestamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Powerline',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('title', models.TextField(verbose_name=20)),
                ('powerline', models.TextField(verbose_name=50)),
                ('voltage', models.IntegerField()),
                ('service_date', models.TextField(verbose_name=10)),
                #('service_date', models.CharField(choices=[('%m/%d/%Y', 'Month Day Year'), ('%m/%Y', 'Month Year')], max_length=10, verbose_name='Date Choice')),
            ],
        ),
    ]
