# Generated by Django 2.2.4 on 2019-12-06 19:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drf_gcmv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=20)),
                ('bore_id', models.CharField(max_length=20)),
                ('instrument', models.CharField(max_length=20)),
                ('chemical_id', models.CharField(max_length=20)),
                ('measurement_value', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'drf_gcmv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_gcmv_Jobid',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name=10)),
                ('label', models.TextField(verbose_name=10)),
            ],
            options={
                'db_table': 'drf_gcmv_jobid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_gcmv_Timestamp',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False)),
                ('label', models.DateTimeField()),
            ],
            options={
                'db_table': 'drf_gcmv_timestamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_mscnt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=20)),
                ('bore_id', models.CharField(max_length=20)),
                ('instrument', models.CharField(max_length=20)),
                ('chemical_id', models.CharField(max_length=20)),
                ('measurement_value', models.CharField(max_length=20)),
                ('units', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('comment', models.CharField(default='', max_length=1000, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'drf_mscnt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_mscnt_Jobid',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name=10)),
                ('label', models.TextField(verbose_name=10)),
            ],
            options={
                'db_table': 'drf_mscnt_jobid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='drf_mscnt_Timestamp',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False)),
                ('label', models.DateTimeField()),
            ],
            options={
                'db_table': 'drf_mscnt_timestamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Powerline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('title', models.TextField(verbose_name=50)),
                ('powerline', models.TextField(verbose_name=20)),
                ('voltage', models.IntegerField()),
                ('service_date', models.TextField(null=True, verbose_name=10)),
            ],
        ),
    ]
