# Generated by Django 2.2.3 on 2019-08-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drf_Jobid',
            table='drf_jobid',
        ),
        migrations.AlterModelTable(
            name='drf_Measurement',
            table='drf_measurement',
        ),
        migrations.AlterModelTable(
            name='drf_Timestamp',
            table='drf_timestamp',
        ),
    ]
