version: '3.7'

services:

  app_dev:
    container_name: quasar-lassares-dev
    build:
      context: .
      dockerfile: Dockerfile.quasar
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
