version: '3.7'
services:
  database:
    image: mdillon/postgis:11 
    container_name: database
    network_mode: host
    ports:
      - 5432:${POSTGRES_PORT:-5432}

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django
    container_name: django
    network_mode: host
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    image: quasar 
    container_name: quasar 
    network_mode: host
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ./quasar/src/statics:/code/statics
      - ./certs/self.signed.crt:/etc/ssl/SSL.crt
      - ./certs/self.signed.key:/etc/ssl/SSL.key
    environment:
      - NGINX_HOST:${NGINX_HOST:-127.0.0.1}

