version: '3.7'

services:
  django:
    build: 
      context: ./
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../django-pfiProject-docker/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./pfiProject/.env.dev
    depends_on:
      - database
  database:
    image: mdillon/postgis:11
    ports:
      - 5432:${SQL_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=database

volumes:
  postgres_data:
